linters:
  ColorVariable:
    enabled: false
  Comment:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  IdSelector:
    enabled: false
  Indentation:
    enabled: false
  LeadingZero:
    enabled: false
  NestingDepth:
    enabled: false
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: false
  SingleLinePerSelector:
    enabled: false
